#ifndef COMMONS_H
#define COMMONS_H

#define STRINGS_ARE_EQUAL( Str1, Str2 ) ( strcmp( (Str1), (Str2) ) == 0 )

typedef enum
{
	SERVER_SUCCESS,
	SERVER_NOT_ENOUGH_CMD_ARGS,
	SERVER_WSA_STARTUP_ERROR,
	SERVER_SOCKET_CREATION_FAILED,
	SERVER_INVALID_IP_ADDRESS,
	SERVER_SOCKET_BINDING_FAILED,
	SERVER_SOCKET_LISTEN_FAILED,
	SERVER_ACCEPT_CONNECTION_FAILED,
	SERVER_MEM_ALLOC_FAILED,
	SERVER_TRANS_FAILED,
	SERVER_UNEXPECTED_MESSAGE,
	SERVER_INVALID_PARAM_VALUE,
	SERVER_RECEIVE_MSG_FAILED
} SERVER_EXIT_CODES;

#endif
