#ifndef COMMONS_H
#define COMMONS_H

typedef enum
{
	SERVER_SUCCESS,
	SERVER_NOT_ENOUGH_CMD_ARGS,
	SERVER_WSA_STARTUP_ERROR,
	SERVER_SOCKET_CREATION_FAILED,
	SERVER_INVALID_IP_ADDRESS,
	SERVER_SOCKET_BINDING_FAILED,
	SERVER_SOCKET_LISTEN_FAILED,
	SERVER_ACCEPT_CONNECTION_FAILED,
	SERVER_MEM_ALLOC_FAILED,
	SERVER_TRANS_FAILED,
	SERVER_UNEXPECTED_MESSAGE,
	SERVER_INVALID_PARAM_VALUE,
	SERVER_RECEIVE_MSG_FAILED,
	SERVER_THREAD_CREATION_FAILED,
	SERVER_CLIENT_DISCONNECTED,
	SERVER_CREATE_MUTEX_FAILED,
	SERVER_ACQUIRE_MUTEX_FAILED,
	SERVER_MUTEX_RELEASE_FAILED,
	SERVER_FILE_OPEN_FAILED,
	SERVER_FILE_EXISTS,
	SERVER_CREATE_EVENT_FAILED,
	SERVER_SET_EVENT_FAILED,
	SERVER_WAIT_FOR_EVENT_FAILED,
	SERVER_DELETE_FILE_FAILED,
	SERVER_WAIT_ERROR
} SERVER_EXIT_CODES;

#endif
