#ifndef COMMONS_H
#define COMMONS_H

typedef enum
{
	CLIENT_SUCCESS,
	CLIENT_NOT_ENOUGH_CMD_ARGS,
	CLIENT_WSA_STARTUP_ERROR,
	CLIENT_SOCKET_CREATION_FAILED,
	CLIENT_INVALID_IP_ADDRESS,
	CLIENT_SOCKET_BINDING_FAILED,
	CLIENT_SOCKET_LISTEN_FAILED,
	CLIENT_ACCEPT_CONNECTION_FAILED
} CLIENT_EXIT_CODES;

typedef enum
{
	CLIENT_REQUEST
} CLIENT_MESSAGE_TYPES;

typedef enum
{
	FIRST_CONNECTION,
	WAITING_SERVER_APPROVAL,
	SERVER_APPROVED,
	MAIN_MENU,
	WAITING_TO_START_GAME,
	PLAY_MOVE
} CLIENT_STATE;

typedef enum
{
	PLAY_VS_PLAYER = 1,
	PLAY_VS_COMPUTER = 2,
	LEADERBOARD = 3,
	QUIT = 4
} USER_CHOICE;

#endif
